import React from 'react'
import Template from "./Template"

const Roman = () => {
  return (
    <>
        <Template name={"Botanical Gardens"} place_num={0} stars={5} mapLink={"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12021.398241567167!2d-74.24711481090594!3d41.12689443340727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c31fc1fe7bde19%3A0x1eba00b53ab0fa00!2sNew%20Jersey%20Botanical%20Garden!5e0!3m2!1sen!2sus!4v1646341443206!5m2!1sen!2sus"} pnumb={"(973) 962-9534"} address={"New Jersey Botanical Garden, 2 Morris Rd, Ringwood, NJ 07456"} hours={"Sun	8AM–8PM Mon 8AM–8PM Tues 8AM–8PM Wed 8AM–8PM Thurs 8AM–8PM Fri 8AM–8PM Sat 8AM–8PM"} website={"https://www.njbg.org/"} faq1q={"Can I bring my dog?"} faq1a={"No pets are allowed."} faq2q={"What is the Parking/Admission Fee?"} faq2a={"$5 Parking for NJ residents and no admission fee."} faq3q={"How long does it take to explore the place?"} faq3a={"The place is very expansive, so try to spend around 3 hours exploring."} h1={"The Park is 96 Acres large"} h2={"Governor Thomas Kean designed the park in 1984"} h3={"The NJ Botanical Gardens were orginally called Skylands."} about={"First formed by Francis Lynde Stetson, the Botanical Gardens, named Skylands Farms at that time, was created. Skylands was sold in 1922 to Clarence Lewis, who turned it into the park into the garden we know it today. Lewis hired prominent architects Feruccio Vitale and Alfred Geiffert to design the park. They added hundreds of bushes and flowers over 30 years, eventually amassing one of the finest collections of plants on the east coast. In 1966, New Jersey purchased some of the land to be officially instituted as a state Park."} thingstoknow={"The New Jersey Botanical Gardens have been a staple of the Garden State since 1966. A part of the Ringwood State Park, New Jersey Division of Parks and Forestry, and Department of Environmental Protection. There are many differnt sections of the garden you can visit today. Perhaps the most far-reaching and famous of these is the Perennial Garden and the Lilac Garde, both of which change scenery with the seasons."} covid={"Masks required for all indoor for all New Jersey State Parks."} addInfo={"A permit is required for professional photography. Feel free to reach out for any volunteering opportunities or to hear about upcoming events."} />
    </>
  )
}

export default Roman